name: mp3_info
description: A package for extracting key meta information from an MP3 file including sample rate, bitrate and duration.
version: 0.1.0
homepage: https://github.com/amugofjava?tab=repositories
author: Ben Hills <ben.hills@amugofjava.me.uk>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
