name: mp3_info
description: A package for extracting key meta information from an MP3 file including sample rate, bitrate and duration. Written in pure Dart.
version: 0.2.3
homepage: https://github.com/amugofjava/mp3_info

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.29.0
